<?php

namespace App\Services\Exams\Grading\Assistants;

use App\Models\Exam\InstructorExamQuestion;
use App\Models\ExamSessionAnswer;
use Illuminate\Support\Facades\Http;
use RuntimeException;

class GoogleGeminiWrittenAnswerGradingProvider implements WrittenAnswerGradingProvider
{
    public function __construct(
        private readonly WrittenAnswerEvaluationPayload $evaluationPayload,
    ) {}

    public function available(): bool
    {
        return filled($this->apiKey());
    }

    public function suggest(ExamSessionAnswer $answer): WrittenAnswerGradingSuggestion
    {
        if (! $this->available()) {
            throw new RuntimeException('Google Gemini API key is not configured.');
        }

        $answer->loadMissing('question.sessionAnswers', 'session.assignment.exam.course', 'session.student.user');
        $question = $answer->question;

        if (! $question instanceof InstructorExamQuestion) {
            throw new RuntimeException('The answer does not have a question to grade.');
        }

        $maxScore = (float) $question->marks;
        $evaluation = $this->evaluationPayload->make($answer);
        $payload = [
            'contents' => [
                [
                    'role' => 'user',
                    'parts' => [
                        ['text' => $this->prompt($evaluation)],
                    ],
                ],
            ],
            'generationConfig' => [
                'temperature' => 0.2,
                'responseMimeType' => 'application/json',
                'responseJsonSchema' => $this->responseSchema(),
            ],
        ];

        $response = Http::timeout((int) config('services.ai_grading.google.timeout', 30))
            ->withHeaders([
                'x-goog-api-key' => $this->apiKey(),
                'Content-Type' => 'application/json',
            ])
            ->post($this->endpoint(), $payload);

        if ($response->failed()) {
            throw new RuntimeException('Google Gemini grading request failed: '.$response->body());
        }

        $text = data_get($response->json(), 'candidates.0.content.parts.0.text');
        $data = is_string($text) ? json_decode($text, true) : null;

        if (! is_array($data)) {
            throw new RuntimeException('Google Gemini returned an invalid grading response.');
        }

        return new WrittenAnswerGradingSuggestion(
            suggestedScore: min(max((float) ($data['suggested_score'] ?? 0), 0), $maxScore),
            maxScore: $maxScore,
            confidence: min(max((float) ($data['confidence'] ?? 0.5), 0), 1),
            feedback: trim((string) ($data['feedback'] ?? 'Review suggested score before saving.')),
            strengths: $this->stringList($data['strengths'] ?? []),
            improvements: $this->stringList($data['improvements'] ?? []),
            provider: 'google_gemini:'.$this->model(),
            rationale: trim((string) ($data['rationale'] ?? 'Suggested from the question requirements, rubric, expected answer, and typed student answer.')),
            providerNote: 'Generated by Google Gemini API. Instructor review is still required before saving the score.',
            rubricAssessment: $this->rubricAssessmentList($data['rubric_assessment'] ?? []),
        );
    }

    private function prompt(array $evaluation): string
    {
        return json_encode([
            'instruction' => 'You are an exam grading assistant. Evaluate only from this JSON package and return JSON that matches the response schema.',
            'hard_rules' => [
                'Grade based on correctness, rubric, expected answer, question difficulty, and submitted answer evidence.',
                'Do not use answer length or word count as the grading basis.',
                'Do not award marks just because the student wrote a long response.',
                'Never exceed the max_score in scoring_policy.',
                'If the answer is blank or unrelated, suggest 0 or a very low score and explain why.',
                'The instructor will review and save the final score.',
            ],
            'evaluation_request' => $evaluation,
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }

    private function responseSchema(): array
    {
        return [
            'type' => 'object',
            'properties' => [
                'suggested_score' => [
                    'type' => 'number',
                    'description' => 'Suggested score in question marks. Must be between 0 and max_score.',
                ],
                'confidence' => [
                    'type' => 'number',
                    'description' => 'Confidence from 0 to 1.',
                ],
                'feedback' => [
                    'type' => 'string',
                    'description' => 'Concise instructor-facing feedback explaining the suggested score.',
                ],
                'strengths' => [
                    'type' => 'array',
                    'items' => ['type' => 'string'],
                ],
                'improvements' => [
                    'type' => 'array',
                    'items' => ['type' => 'string'],
                ],
                'rationale' => [
                    'type' => 'string',
                    'description' => 'Plain-language explanation of why this score was suggested.',
                ],
                'rubric_assessment' => [
                    'type' => 'array',
                    'items' => [
                        'type' => 'object',
                        'properties' => [
                            'criterion' => ['type' => 'string'],
                            'score' => ['type' => 'number'],
                            'max_score' => ['type' => 'number'],
                            'evidence' => ['type' => 'string'],
                            'notes' => ['type' => 'string'],
                        ],
                        'required' => ['criterion', 'score', 'max_score', 'evidence', 'notes'],
                    ],
                ],
            ],
            'required' => ['suggested_score', 'confidence', 'feedback', 'strengths', 'improvements', 'rationale', 'rubric_assessment'],
        ];
    }

    private function endpoint(): string
    {
        return rtrim((string) config('services.ai_grading.google.endpoint'), '/')
            .'/v1beta/models/'.$this->model().':generateContent';
    }

    private function apiKey(): ?string
    {
        return config('services.ai_grading.google.api_key');
    }

    private function model(): string
    {
        return (string) config('services.ai_grading.google.model', 'gemini-2.5-flash');
    }

    private function stringList(mixed $value): array
    {
        return collect(is_array($value) ? $value : [])
            ->map(fn ($item): string => trim((string) $item))
            ->filter()
            ->values()
            ->all();
    }

    private function rubricAssessmentList(mixed $value): array
    {
        return collect(is_array($value) ? $value : [])
            ->filter(fn ($item): bool => is_array($item))
            ->map(fn (array $item): array => [
                'criterion' => trim((string) ($item['criterion'] ?? 'Criterion')),
                'score' => (float) ($item['score'] ?? 0),
                'max_score' => (float) ($item['max_score'] ?? 0),
                'evidence' => trim((string) ($item['evidence'] ?? '')),
                'notes' => trim((string) ($item['notes'] ?? '')),
            ])
            ->values()
            ->all();
    }
}
